# Autogenerated by nbdev

d = { 'settings': { 'branch': '',
                'doc_baseurl': '/trail24',
                'doc_host': 'https://.github.io',
                'git_url': 'https://github.com//trail24',
                'lib_path': 'trail24'},
  'syms': {'trail24.core': {'trail24.core.foo': ('core.html#foo', 'trail24/core.py')}}}
