"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_compression.onnx.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/03_compression.onnx.ipynb 3
import torch
import torch.nn as nn
from onnxruntime.quantization import quantize_dynamic, QuantType
