project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    contents:
    - section: Data
      contents:
      - 00_data.preprocess.ipynb
      - 01_data.cluster.ipynb
    - section: Experiments
      contents:
      - 05_experiment.preprocess.ipynb
      - 06_experiment.tahercluster.ipynb
      - 06_experiment.cluster.ipynb
      - 07_experiment.interpret.ipynb

metadata-files: [nbdev.yml]
